// Package wordlist provides a encoders and a decoder for WebWormhole codes.
package wordlist

import (
	"encoding/binary"
	"strings"
)

// Encoding is a string encoding for a vector of bytes.
type Encoding interface {
	// Encode returns the string encoding for slot and pass.
	Encode(slot int, pass []byte) string
	// Encode returns the slot and pass encoded by code.
	Decode(code string) (slot int, pass []byte)
	// Match returns the first word in the word list that has prefix prefix.
	Match(prefix string) string
}

var (
	// EnWords is based on the EFF short wordlist, filtered by unique soundex.
	// https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases
	// Credit to Nick Moore https://nick.zoic.org/art/shorter-words-list/
	//
	// TODO It's a global variable for now. We'll need to figure out an easier
	// way to switch between multiple encoding for different languages etc.
	EnWords Encoding = enWords
)

// wordEncodings map 512 words into the 256 values of bytes and a parity bit.
type wordEncoding []string

// Encode returns the words representing the bytes in buf.
func (list wordEncoding) Encode(slot int, pass []byte) string {
	if len(pass) == 0 {
		return ""
	}
	slotbytes := make([]byte, binary.MaxVarintLen64)
	n := binary.PutUvarint(slotbytes, uint64(slot))
	slotbytes = slotbytes[:n]

	words := make([]string, n+len(pass))
	for i := range slotbytes {
		words[i] = list[int(slotbytes[i])*2+i%2]
	}
	for i := range pass {
		words[n+i] = list[int(pass[i])*2+(n+i)%2]
	}
	return strings.Join(words, "-")
}

// Decode decodes the code of into a slot and a password. Invalid codes
// return a 0 slot and a nil pass.
func (list wordEncoding) Decode(code string) (slot int, pass []byte) {
	// White space and - are interchangable.
	code = strings.ReplaceAll(code, "-", " ")
	// Space can turn into + in URLs.
	code = strings.ReplaceAll(code, "+", " ")
	parts := strings.Fields(code)

	buf := make([]byte, len(parts))
	parity := 1
	for i := range parts {
		j, ok := list.indexOf(parts[i])
		if !ok {
			return 0, nil
		}
		buf[i] = byte(j / 2)
		if parity == i%2 {
			return 0, nil
		}
		parity = i % 2
	}

	s, n := binary.Uvarint(buf)
	if n <= 0 {
		return 0, nil
	}
	return int(s), buf[n:]
}

func (list wordEncoding) indexOf(word string) (i int, ok bool) {
	for i := range list {
		if strings.EqualFold(word, list[i]) {
			return i, true
		}
	}
	return 0, false
}

// Match returns the first word that begins with prefix, or the empty string
// if none match.
func (list wordEncoding) Match(prefix string) string {
	if prefix == "" {
		return ""
	}
	for i := range list {
		if strings.HasPrefix(list[i], prefix) {
			return list[i]
		}
	}
	return ""
}

var enWords = wordEncoding{
	"acorn", "acre",
	"acts", "afar",
	"affix", "aged",
	"agent", "agile",
	"aging", "agony",
	"aide", "aids",
	"aim", "alarm",
	"alike", "alive",
	"aloe", "aloft",
	"alone", "amend",
	"ample", "amuse",
	"angel", "anger",
	"apple", "april",
	"apron", "area",
	"argue", "armed",
	"armor", "army",
	"arson", "art",
	"atlas", "atom",
	"avert", "avoid",
	"axis", "bacon",
	"baker", "balmy",
	"barn", "basil",
	"baton", "bats",
	"blank", "blast",
	"blend", "blimp",
	"blob", "blog",
	"blurt", "boil",
	"bok", "bolt",
	"bony", "bribe",
	"bring", "broad",
	"broil", "broke",
	"bud", "bunch",
	"bunt", "bust",
	"calm", "canal",
	"candy", "card",
	"case", "cedar",
	"chump", "civic",
	"civil", "clamp",
	"clasp", "class",
	"clay", "clear",
	"cleft", "clerk",
	"cling", "clip",
	"cold", "come",
	"comic", "cork",
	"cost", "cover",
	"craft", "cramp",
	"crank", "crisp",
	"crop", "crown",
	"crust", "cub",
	"cupid", "cure",
	"curl", "cut",
	"cycle", "dab",
	"dad", "dart",
	"deal", "debt",
	"debug", "decaf",
	"decal", "decor",
	"dent", "dig",
	"dimly", "ditch",
	"doing", "donor",
	"down", "drab",
	"drank", "dress",
	"drift", "drill",
	"drum", "dry",
	"dust", "early",
	"earth", "east",
	"eaten", "ebony",
	"echo", "edge",
	"eel", "elder",
	"elf", "elk",
	"elm", "elude",
	"elves", "email",
	"emit", "empty",
	"emu", "enter",
	"envoy", "equal",
	"erase", "error",
	"erupt", "evade",
	"even", "evict",
	"evil", "evoke",
	"fable", "fact",
	"fall", "fang",
	"femur", "fend",
	"fetal", "fetch",
	"fever", "fifth",
	"film", "final",
	"fit", "five",
	"flag", "fled",
	"fling", "flint",
	"flip", "flirt",
	"flyer", "foam",
	"fox", "frail",
	"fray", "fresh",
	"from", "front",
	"frost", "fruit",
	"gap", "gas",
	"gem", "genre",
	"gift", "given",
	"giver", "glad",
	"glass", "goal",
	"golf", "gong",
	"grab", "grant",
	"grasp", "grass",
	"green", "grew",
	"grid", "grill",
	"gut", "habit",
	"halt", "harm",
	"hasty", "hatch",
	"haven", "hazel",
	"help", "herbs",
	"hers", "hub",
	"hug", "hull",
	"human", "hump",
	"hung", "hunt",
	"hurry", "hurt",
	"hut", "ice",
	"icing", "icon",
	"igloo", "image",
	"ion", "iron",
	"item", "ivory",
	"ivy", "jam",
	"jet", "job",
	"jog", "jolt",
	"judge", "july",
	"jump", "junky",
	"jury", "keep",
	"keg", "kept",
	"kilt", "king",
	"kite", "knee",
	"knelt", "koala",
	"ladle", "lake",
	"land", "last",
	"latch", "left",
	"legal", "lens",
	"level", "lid",
	"lilac", "lily",
	"limb", "line",
	"lip", "liver",
	"lunar", "lure",
	"lurk", "maker",
	"mango", "manor",
	"map", "march",
	"mardi", "marry",
	"match", "malt",
	"mom", "most",
	"motor", "mount",
	"mud", "mug",
	"mulch", "mule",
	"mumbo", "mural",
	"nag", "nail",
	"name", "nap",
	"near", "nerd",
	"net", "next",
	"ninth", "oak",
	"oat", "ocean",
	"oil", "old",
	"olive", "omen",
	"only", "open",
	"opera", "opt",
	"ounce", "outer",
	"oval", "pagan",
	"palm", "pants",
	"paper", "park",
	"party", "patch",
	"pep", "perm",
	"pest", "petal",
	"petri", "plank",
	"plant", "plot",
	"plus", "pod",
	"poem", "poker",
	"polar", "pond",
	"prank", "print",
	"prism", "proof",
	"props", "pry",
	"pug", "pull",
	"pulp", "punk",
	"pupil", "quake",
	"query", "quill",
	"quit", "rabid",
	"radar", "raft",
	"ramp", "rank",
	"rant", "recap",
	"relax", "reply",
	"rerun", "rigor",
	"ritzy", "river",
	"robin", "rope",
	"rug", "ruin",
	"rule", "rust",
	"rut", "salt",
	"same", "scale",
	"scan", "scold",
	"score", "scorn",
	"scrap", "sect",
	"self", "send",
	"set", "seven",
	"share", "shirt",
	"shrug", "silk",
	"silo", "sip",
	"siren", "skip",
	"skirt", "sky",
	"slam", "slang",
	"slept", "slurp",
	"small", "smirk",
	"smog", "snap",
	"snare", "snarl",
	"snort", "speak",
	"spent", "spill",
	"sport", "spot",
	"spur", "stamp",
	"stand", "stark",
	"start", "stem",
	"sting", "stir",
	"stole", "stop",
	"storm", "suds",
	"surf", "swirl",
	"tag", "tall",
	"talon", "tamer",
	"tank", "taper",
	"taps", "tart",
	"taste", "theft",
	"thumb", "tidal",
	"tidy", "tiger",
	"tilt", "tint",
	"tiny", "train",
	"trap", "trek",
	"trend", "trial",
	"trunk", "try",
	"tulip", "tutor",
	"uncle", "uncut",
	"unify", "union",
	"unit", "upon",
	"upper", "urban",
	"used", "user",
	"utter", "value",
	"vapor", "vegan",
	"venue", "vest",
	"vice", "viral",
	"virus", "visor",
	"vocal", "void",
	"volt", "voter",
	"wad", "wafer",
	"wager", "wagon",
	"walk", "wasp",
	"watch", "water",
	"widen", "wife",
	"wilt", "wind",
	"wing", "wiry",
	"wok", "wolf",
	"womb", "wool",
	"word", "work",
	"woven", "wrist",
	"xerox", "yam",
	"yard", "year",
	"yeast", "yelp",
	"yield", "yodel",
	"yoga", "zebra",
	"zero", "zesty",
	"zippy", "zone",
}

// pgpWords is the PGP word list encoding.
// https://en.wikipedia.org/wiki/PGP_word_list
var pgpWords = wordEncoding{
	"aardvark", "adroitness",
	"absurd", "adviser",
	"accrue", "aftermath",
	"acme", "aggregate",
	"adrift", "alkali",
	"adult", "almighty",
	"afflict", "amulet",
	"ahead", "amusement",
	"aimless", "antenna",
	"algol", "applicant",
	"allow", "apollo",
	"alone", "armistice",
	"ammo", "article",
	"ancient", "asteroid",
	"apple", "atlantic",
	"artist", "atmosphere",
	"assume", "autopsy",
	"athens", "babylon",
	"atlas", "backwater",
	"aztec", "barbecue",
	"baboon", "belowground",
	"backfield", "bifocals",
	"backward", "bodyguard",
	"banjo", "bookseller",
	"beaming", "borderline",
	"bedlamp", "bottomless",
	"beehive", "bradbury",
	"beeswax", "bravado",
	"befriend", "brazilian",
	"belfast", "breakaway",
	"berserk", "burlington",
	"billiard", "businessman",
	"bison", "butterfat",
	"blackjack", "camelot",
	"blockade", "candidate",
	"blowtorch", "cannonball",
	"bluebird", "capricorn",
	"bombast", "caravan",
	"bookshelf", "caretaker",
	"brackish", "celebrate",
	"breadline", "cellulose",
	"breakup", "certify",
	"brickyard", "chambermaid",
	"briefcase", "cherokee",
	"burbank", "chicago",
	"button", "clergyman",
	"buzzard", "coherence",
	"cement", "combustion",
	"chairlift", "commando",
	"chatter", "company",
	"checkup", "component",
	"chisel", "concurrent",
	"choking", "confidence",
	"chopper", "conformist",
	"christmas", "congregate",
	"clamshell", "consensus",
	"classic", "consulting",
	"classroom", "corporate",
	"cleanup", "corrosion",
	"clockwork", "councilman",
	"cobra", "crossover",
	"commence", "crucifix",
	"concert", "cumbersome",
	"cowbell", "customer",
	"crackdown", "dakota",
	"cranky", "decadence",
	"crowfoot", "december",
	"crucial", "decimal",
	"crumpled", "designing",
	"crusade", "detector",
	"cubic", "detergent",
	"dashboard", "determine",
	"deadbolt", "dictator",
	"deckhand", "dinosaur",
	"dogsled", "direction",
	"dragnet", "disable",
	"drainage", "disbelief",
	"dreadful", "disruptive",
	"drifter", "distortion",
	"dropper", "document",
	"drumbeat", "embezzle",
	"drunken", "enchanting",
	"dupont", "enrollment",
	"dwelling", "enterprise",
	"eating", "equation",
	"edict", "equipment",
	"egghead", "escapade",
	"eightball", "eskimo",
	"endorse", "everyday",
	"endow", "examine",
	"enlist", "existence",
	"erase", "exodus",
	"escape", "fascinate",
	"exceed", "filament",
	"eyeglass", "finicky",
	"eyetooth", "forever",
	"facial", "fortitude",
	"fallout", "frequency",
	"flagpole", "gadgetry",
	"flatfoot", "galveston",
	"flytrap", "getaway",
	"fracture", "glossary",
	"framework", "gossamer",
	"freedom", "graduate",
	"frighten", "gravity",
	"gazelle", "guitarist",
	"geiger", "hamburger",
	"glitter", "hamilton",
	"glucose", "handiwork",
	"goggles", "hazardous",
	"goldfish", "headwaters",
	"gremlin", "hemisphere",
	"guidance", "hesitate",
	"hamlet", "hideaway",
	"highchair", "holiness",
	"hockey", "hurricane",
	"indoors", "hydraulic",
	"indulge", "impartial",
	"inverse", "impetus",
	"involve", "inception",
	"island", "indigo",
	"jawbone", "inertia",
	"keyboard", "infancy",
	"kickoff", "inferno",
	"kiwi", "informant",
	"klaxon", "insincere",
	"locale", "insurgent",
	"lockup", "integrate",
	"merit", "intention",
	"minnow", "inventive",
	"miser", "istanbul",
	"mohawk", "jamaica",
	"mural", "jupiter",
	"music", "leprosy",
	"necklace", "letterhead",
	"neptune", "liberty",
	"newborn", "maritime",
	"nightbird", "matchmaker",
	"oakland", "maverick",
	"obtuse", "medusa",
	"offload", "megaton",
	"optic", "microscope",
	"orca", "microwave",
	"payday", "midsummer",
	"peachy", "millionaire",
	"pheasant", "miracle",
	"physique", "misnomer",
	"playhouse", "molasses",
	"pluto", "molecule",
	"preclude", "montana",
	"prefer", "monument",
	"preshrunk", "mosquito",
	"printer", "narrative",
	"prowler", "nebula",
	"pupil", "newsletter",
	"puppy", "norwegian",
	"python", "october",
	"quadrant", "ohio",
	"quiver", "onlooker",
	"quota", "opulent",
	"ragtime", "orlando",
	"ratchet", "outfielder",
	"rebirth", "pacific",
	"reform", "pandemic",
	"regain", "pandora",
	"reindeer", "paperweight",
	"rematch", "paragon",
	"repay", "paragraph",
	"retouch", "paramount",
	"revenge", "passenger",
	"reward", "pedigree",
	"rhythm", "pegasus",
	"ribcage", "penetrate",
	"ringbolt", "perceptive",
	"robust", "performance",
	"rocker", "pharmacy",
	"ruffled", "phonetic",
	"sailboat", "photograph",
	"sawdust", "pioneer",
	"scallion", "pocketful",
	"scenic", "politeness",
	"scorecard", "positive",
	"scotland", "potato",
	"seabird", "processor",
	"select", "provincial",
	"sentence", "proximate",
	"shadow", "puberty",
	"shamrock", "publisher",
	"showgirl", "pyramid",
	"skullcap", "quantity",
	"skydive", "racketeer",
	"slingshot", "rebellion",
	"slowdown", "recipe",
	"snapline", "recover",
	"snapshot", "repellent",
	"snowcap", "replica",
	"snowslide", "reproduce",
	"solo", "resistor",
	"southward", "responsive",
	"soybean", "retraction",
	"spaniel", "retrieval",
	"spearhead", "retrospect",
	"spellbind", "revenue",
	"spheroid", "revival",
	"spigot", "revolver",
	"spindle", "sandalwood",
	"spyglass", "sardonic",
	"stagehand", "saturday",
	"stagnate", "savagery",
	"stairway", "scavenger",
	"standard", "sensation",
	"stapler", "sociable",
	"steamship", "souvenir",
	"sterling", "specialist",
	"stockman", "speculate",
	"stopwatch", "stethoscope",
	"stormy", "stupendous",
	"sugar", "supportive",
	"surmount", "surrender",
	"suspense", "suspicious",
	"sweatband", "sympathy",
	"swelter", "tambourine",
	"tactics", "telephone",
	"talon", "therapist",
	"tapeworm", "tobacco",
	"tempest", "tolerance",
	"tiger", "tomorrow",
	"tissue", "torpedo",
	"tonic", "tradition",
	"topmost", "travesty",
	"tracker", "trombonist",
	"transit", "truncated",
	"trauma", "typewriter",
	"treadmill", "ultimate",
	"trojan", "undaunted",
	"trouble", "underfoot",
	"tumor", "unicorn",
	"tunnel", "unify",
	"tycoon", "universe",
	"uncut", "unravel",
	"unearth", "upcoming",
	"unwind", "vacancy",
	"uproot", "vagabond",
	"upset", "vertigo",
	"upshot", "virginia",
	"vapor", "visitor",
	"village", "vocalist",
	"virus", "voyager",
	"vulcan", "warranty",
	"waffle", "waterloo",
	"wallet", "whimsical",
	"watchword", "wichita",
	"wayside", "wilmington",
	"willow", "wyoming",
	"woodlark", "yesteryear",
	"zulu", "yucatan",
}
