#!/bin/bash

name="webwormhole-$(date -u +%Y%m%d%H%M%S)"
dir="$(mktemp -d)"
trap "rm -rf $dir" EXIT

docker build -f tools/Dockerfile -t webwormhole .
linuxkit build -format raw-bios -dir $dir tools/linuxkit.yaml
mv "$dir/linuxkit-bios.img" "$HOME/Desktop/$name.img"
